//Partly generated by AI, the logic of course,
// the ui is all me, thought id point that out

import 'package:flutter/material.dart';
import 'package:notes/common/widgets/custom_app_bar.dart';
import 'package:notes/constants/strings.dart';
import 'package:notes/feature_mobile/screens/note_screen.dart';
import 'package:notes/feature_mobile/widgets/no_note_widget.dart';
import 'package:provider/provider.dart';
import 'package:uuid/uuid.dart';
import '../../common/models/note_model.dart';
import '../../common/providers/note_provider.dart';

class ComputerHomeScreen extends StatefulWidget {
  final Widget noteView;

  const ComputerHomeScreen({
    super.key,
    required this.noteView,
  });

  @override
  State<ComputerHomeScreen> createState() => _ComputerHomeScreenState();
}

class _ComputerHomeScreenState extends State<ComputerHomeScreen>
    with SingleTickerProviderStateMixin {
  late AnimationController _animationController;
  late Animation<double> _drawerAnimation;

  bool _isDrawerOpen = true;
  final uuid = Uuid();

  double _targetDrawerWidth = 300.0;
  final double _collapsedWidth = 0.0;
  bool _isHovered = false;

  @override
  void initState() {
    super.initState();
    _animationController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 250),
    );

    _drawerAnimation = CurvedAnimation(
      parent: _animationController,
      curve: Curves.easeInOut,
    );

    _animationController.value = 1.0;
  }

  @override
  void dispose() {
    _animationController.dispose();
    super.dispose();
  }

  void toggleDrawer() {
    setState(() {
      _isDrawerOpen = !_isDrawerOpen;
      if (_isDrawerOpen) {
        _animationController.forward();
      } else {
        _animationController.reverse();
      }
    });
  }

  void createNewNote() async {
    final id = uuid.v4();
    final note = NoteModel(
      uuid: id,
      content: '',
      createdDate: DateTime.now(),
      updatedDate: DateTime.now(),
      isPinned: false,
    );
    await context.read<NoteProvider>().saveNote(note);
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context).colorScheme;
    final noteProvider = context.watch<NoteProvider>();

    return Scaffold(
      body: AnimatedBuilder(
        animation: _drawerAnimation,
        builder: (context, child) {
          final currentDrawerWidth = Tween<double>(
            begin: _collapsedWidth,
            end: _targetDrawerWidth,
          ).evaluate(_drawerAnimation);

          return Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                bottom: 0,
                width: currentDrawerWidth,
                child: Scaffold(
                  floatingActionButton: currentDrawerWidth > 100
                      ? FloatingActionButton(
                          onPressed: createNewNote,
                          child: const Icon(Icons.add),
                        )
                      : null,
                  appBar: CustomAppBar(
                    buttonType: AppBarButtonType.custom,
                    customIcon: Icons.settings,
                    title: 'Menu',
                  ),
                  body: noteProvider.notes.isEmpty
                      ? NoNoteWidget()
                      : widget.noteView,
                ),
              ),
              Positioned(
                left: currentDrawerWidth,
                right: 0,
                top: 0,
                bottom: 0,
                child: Scaffold(
                  appBar: CustomAppBar(
                    buttonType: AppBarButtonType.custom,
                    title: Strings.note,
                    customIcon:
                        _isDrawerOpen ? Icons.chevron_left_rounded : Icons.menu,
                    onBackPress: toggleDrawer,
                  ),
                  body: noteProvider.noteModel != null
                      ? Consumer<NoteProvider>(
                          builder: (context, noteProvider, child) {
                            return const NoteScreen();
                          },
                        )
                      : const NoNoteWidget(),
                ),
              ),
              if (_isDrawerOpen)
                Positioned(
                  left: currentDrawerWidth - 15,
                  top: 0,
                  bottom: 0,
                  width: 30,
                  child: MouseRegion(
                    onEnter: (_) => setState(() => _isHovered = true),
                    onExit: (_) => setState(() => _isHovered = false),
                    cursor: SystemMouseCursors.resizeLeftRight,
                    child: Stack(
                      alignment: Alignment.center,
                      children: [
                        VerticalDivider(
                          thickness: 1,
                          color: theme.primary,
                        ),
                        GestureDetector(
                          behavior: HitTestBehavior.translucent,
                          onHorizontalDragUpdate: (details) {
                            setState(() {
                              _targetDrawerWidth += details.delta.dx;
                              _targetDrawerWidth =
                                  _targetDrawerWidth.clamp(150.0, 500.0);
                            });
                          },
                          child: _isHovered
                              ? Container(
                                  padding: const EdgeInsets.all(5),
                                  decoration: BoxDecoration(
                                    shape: BoxShape.circle,
                                    color: theme.primary,
                                  ),
                                  child: const Icon(
                                    Icons.drag_handle,
                                    size: 16,
                                    color: Colors.white,
                                  ),
                                )
                              : null,
                        )
                      ],
                    ),
                  ),
                ),
            ],
          );
        },
      ),
    );
  }
}
