//Partly generated by AI, the logic of course,
// the ui is all me, thought id point that out

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:notes/common/providers/system_settings_provider.dart';
import 'package:notes/common/widgets/custom_app_bar.dart';
import 'package:notes/constants/strings.dart';
import 'package:notes/feature_computer/widgets/computer_note_drawer.dart';
import 'package:notes/feature_mobile/screens/note_screen.dart';
import 'package:provider/provider.dart';
import 'package:uuid/uuid.dart';
import '../../common/models/note_model.dart';
import '../../common/providers/note_provider.dart';
import '../../common/widgets/no_note_widget.dart';
import '../../constants/app_images.dart';
import 'computer_settings_screen.dart';

class ComputerHomeScreen extends StatefulWidget {
  final Widget noteView;

  const ComputerHomeScreen({
    super.key,
    required this.noteView,
  });

  @override
  State<ComputerHomeScreen> createState() => _ComputerHomeScreenState();
}

class _ComputerHomeScreenState extends State<ComputerHomeScreen>
    with SingleTickerProviderStateMixin {
  late AnimationController _animationController;
  late Animation<double> _drawerAnimation;
  Timer? _debouncer;

  bool _isDrawerOpen = true;
  final uuid = Uuid();

  // double _targetDrawerWidth = 300.0;
  final double _collapsedWidth = 0.0;
  bool _isHovered = false;

  void onSideBarWidthChange(DragUpdateDetails details) {
    final settingsProvider = context.read<SystemSettingsProvider>();
    final width =
        (settingsProvider.systemSettingsModel.sideBarWidth + details.delta.dx)
            .clamp(150, 500)
            .toDouble();
    settingsProvider.setSideBarWidth(width, shouldSave: false);
    if (_debouncer?.isActive ?? false) _debouncer?.cancel();
    _debouncer = Timer(const Duration(milliseconds: 300), () {
      settingsProvider.setSideBarWidth(width);
    });
  }

  @override
  void initState() {
    super.initState();
    _animationController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 250),
    );

    _drawerAnimation = CurvedAnimation(
      parent: _animationController,
      curve: Curves.easeInOut,
    );

    _animationController.value = 1.0;
  }

  @override
  void dispose() {
    _animationController.dispose();
    super.dispose();
  }

  void toggleDrawer() {
    setState(() {
      _isDrawerOpen = !_isDrawerOpen;
      if (_isDrawerOpen) {
        _animationController.forward();
      } else {
        _animationController.reverse();
      }
    });
  }

  void createNewNote() async {
    final id = uuid.v4();
    final note = NoteModel(
      uuid: id,
      content: '',
      createdDate: DateTime.now(),
      updatedDate: DateTime.now(),
      isPinned: false,
    );
    await context.read<NoteProvider>().saveNote(note);
  }

  Future<dynamic> settingsDialog(BuildContext context) {
    return showDialog(
      context: context,
      builder: (context) {
        return AlertDialog(
          contentPadding: EdgeInsets.zero,
          content: ComputerSettingsScreen(),
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context).colorScheme;
    final noteProvider = context.watch<NoteProvider>();
    final settingsProvider = context.watch<SystemSettingsProvider>();

    return Scaffold(
      body: AnimatedBuilder(
        animation: _drawerAnimation,
        builder: (context, child) {
          final currentDrawerWidth = Tween<double>(
            begin: _collapsedWidth,
            end: settingsProvider.systemSettingsModel.sideBarWidth,
          ).evaluate(_drawerAnimation);

          return Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                bottom: 0,
                width: currentDrawerWidth,
                child: Scaffold(
                  floatingActionButton: currentDrawerWidth > 100
                      ? FloatingActionButton(
                          onPressed: createNewNote,
                          child: const Icon(Icons.add),
                        )
                      : null,
                  appBar: CustomAppBar(
                    buttonType: AppBarButtonType.custom,
                    customIcon: Icons.settings,
                    title: Strings.menu,
                    onBackPress: () async {
                      await settingsDialog(context);
                    },
                  ),
                  body: noteProvider.notes.isEmpty
                      ? const NoNoteWidget(
                          message: Strings.addYourFirst,
                          image: AppImages.noNotes,
                        )
                      : widget.noteView,
                ),
              ),
              Positioned(
                left: currentDrawerWidth,
                right: 0,
                top: 0,
                bottom: 0,
                child: Scaffold(
                  endDrawer: ComputerNoteDrawer(),
                  body: noteProvider.notes.isNotEmpty
                      ? noteProvider.noteModel != null
                          ? Consumer<NoteProvider>(
                              builder: (context, noteProvider, child) {
                                return NoteScreen(
                                  isDrawerOpen: _isDrawerOpen,
                                  toggleDrawer: () {
                                    toggleDrawer();
                                  },
                                );
                              },
                            )
                          : NoNoteWidget(
                              message: Strings.openUpNote,
                              image: AppImages.openNote,
                            )
                      : const NoNoteWidget(
                          message: Strings.addYourFirst,
                          image: AppImages.noNotes,
                        ),
                ),
              ),
              if (_isDrawerOpen)
                Positioned(
                  left: currentDrawerWidth - 15,
                  top: 0,
                  bottom: 0,
                  width: 30,
                  child: MouseRegion(
                    onEnter: (_) => setState(() => _isHovered = true),
                    onExit: (_) => setState(() => _isHovered = false),
                    cursor: SystemMouseCursors.resizeLeftRight,
                    child: Stack(
                      alignment: Alignment.center,
                      children: [
                        VerticalDivider(
                          thickness: 1,
                          color: theme.primary,
                        ),
                        GestureDetector(
                          behavior: HitTestBehavior.translucent,
                          onHorizontalDragUpdate: (details) {
                            onSideBarWidthChange(details);
                          },
                          child: _isHovered
                              ? Container(
                                  padding: const EdgeInsets.all(5),
                                  decoration: BoxDecoration(
                                    shape: BoxShape.circle,
                                    color: theme.primary,
                                  ),
                                  child: const Icon(
                                    Icons.drag_handle,
                                    size: 16,
                                    color: Colors.white,
                                  ),
                                )
                              : null,
                        )
                      ],
                    ),
                  ),
                ),
            ],
          );
        },
      ),
    );
  }
}
